#!/bin/sh /etc/rc.common
START=99
STOP=10

USE_PROCD=1

PROG=/usr/sbin/lora_pkt_fwd_1302
CONFIGFILE=/etc/config/global_conf.json.sx1250.EU868

start_service()
{
        include /lib/functions

        logger "lora_pkt_fwd: Start"
        config_load lora_pkt_fwd_1302

        echo "TeleLoRa: Start lora_pkt_fwd"

        procd_open_instance
        procd_set_param command $PROG -c ${CONFIGFILE}
        procd_set_param respawn

        procd_set_param stdout 1
        procd_set_param stderr 1

        procd_close_instance
}

stop_service() {
        echo "TeleLoRa: Stop lora_pkt_fwd"
        logger "lora_pkt_fwd: Stop"
        killall lora_pkt_fwd_1302
}

